set HOSTS="C:\Windows\System32\drivers\etc\hosts"

del %HOSTS%

echo $IP_ADDRESS SVC-CIC-CERT.$CLIENT-V4.local SVC-CIC-CERT >>%HOSTS%
echo $IP_ADDRESS SVC-BBDD1.$CLIENT-V4.local SVC-BBDD1 >>%HOSTS%

echo. >>%HOSTS%
echo $IP_ADDRESS SVC-CIC1.$CLIENT-V4.local SVC-CIC1 >>%HOSTS%
echo $IP_ADDRESS SVC-CIC2.$CLIENT-V4.local SVC-CIC2 >>%HOSTS%
echo $IP_ADDRESS SVCTICLUSV4PRO.$CLIENT-V4.local SVCTICLUSV4PRO >>%HOSTS%
echo $IP_ADDRESS SVC-SRS.$CLIENT-V4.local SVC-SRS >>%HOSTS%

echo. >>%HOSTS%
echo $IP_ADDRESS SVCTIMSR1-ALC.$CLIENT-V4.local SVCTIMSR1-ALC >>%HOSTS%
echo $IP_ADDRESS SVCTIMSR2-ALC.$CLIENT-V4.local SVCTIMSR2-ALC >>%HOSTS%
echo $IP_ADDRESS SVCTIMSR3-ALC.$CLIENT-V4.local SVCTIMSR3-ALC >>%HOSTS%
echo $IP_ADDRESS SVCTIMSR4-ALC$CLIENT-V4.local SVCTIMSR4-ALC >>%HOSTS%
echo $IP_ADDRESS SVCTIMSR5-ALC$CLIENT-V4.local SVCTIMSR5-ALC >>%HOSTS%
echo $IP_ADDRESS SVCTIMSR6-ALC$CLIENT-V4.local SVCTIMSR6-ALC >>%HOSTS%
echo $IP_ADDRESS SVC-RCS1.$CLIENT-V4.local SVC-RCS1 >>%HOSTS%
echo $IP_ADDRESS SVC-RCS2.$CLIENT-V4.local SVC-RCS2 >>%HOSTS%

echo. >>%HOSTS%
echo $IP_ADDRESS elaaemrpud00.risorse.$CLIENT >>%HOSTS%
echo $IP_ADDRESS svc-csf-cert svc-csf-cert.$CLIENT-V4.local >>%HOSTS%
echo $IP_ADDRESS svc-csf svc-csf.$CLIENT-V4.local >>%HOSTS%

notepad %HOSTS%
